# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dbud <marvin@42.fr>                        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/07/24 22:15:52 by dbud              #+#    #+#              #
#    Updated: 2016/07/24 22:16:11 by dbud             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = eval_expr

SRC = eval_expr.c eval_main.c

all:
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)

clean:
	rm -f $(NAME)

fclean: clean

re: clean all
